name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER }}
          username: ec2-user
          key: ${{ secrets.SSH_EC2 }}
          script: |
            # Créer le répertoire s'il n'existe pas
            cd /var/www/tp_actions
            git pull origin master
            npm install
            npm start 

