name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER }}
          username: ec2-user
          key: ${{ secrets.SSH_EC2 }}
          script: |
            cd /var/www/tp_actions
            if [ ! -d ".git" ]; then
        	git https://github.com/Mohamed-Ayoub-HAJJAR/tp_actions.git . 
      	    else
        	git pull origin master
      	    fi
            npm install
            npm start
