- name: Deploy to EC2 via SSH
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_SERVER }}
    username: ec2-user
    key: ${{ secrets.SSH_EC2 }}
    script: |
      # Si le répertoire existe déjà, le supprimer
      if [ -d "/var/www/tp_actions" ]; then
        rm -rf /var/www/tp_actions/*
      else
        mkdir -p /var/www/tp_actions
      fi
      
      cd /var/www/tp_actions
      git clone https://github.com/Mohamed-Ayoub-HAJJAR/tp_actions.git .
      npm install
      npm start  # Remplace par pm2 start app si tu utilises pm2

